baseURL = "https://plusquamperfect.pages.dev"
languageCode = "en-us"
title = "plusquamperfect"
theme = "papermod"

[params]
  author = "admin"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  math = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
