baseURL = "https://plusquamperfect.pages.dev/"
languageCode = "en"
title = "plusquamperfect"
theme = "papermod"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
  author = "admin"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    title = "plusquamperfect"
    params.homeInfoParams.Title = "Welcome to plusquamperfect"
    params.homeInfoParams.Content = "This space is for writing, notes, and experiments in thought."

  [languages.ru]
    languageName = "Русский"
    weight = 2
    contentDir = "content/ru"
    title = "плюсквамперфект"
    params.homeInfoParams.Title = "Добро пожаловать"
    params.homeInfoParams.Content = "Это место для заметок, экспериментов и размышлений."

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30
